# https://buildvirtual.net/deploy-a-kubernetes-cluster-using-ansible/#
--- 
- name: copy kubernetes config file
  copy:
    src: ../files/kubeadm-master.yaml
    dest: /home/{{ user }}/kubeadm-master.yaml

# add advertise IP and Pod subnetwork to YAML configuration file 
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html#examples
- name: add advertise address to kubernetes config
  lineinfile:
    path: /home/{{ user }}/kubeadm-master.yaml
    search_string: "  advertiseAddress:"
    line: "  advertiseAddress: {{ master_ip }}"

- name: add pod subnetwork to kubernetes config
  lineinfile:
    path: /home/{{ user }}/kubeadm-master.yaml
    search_string: "  podSubnet:"
    line: "  podSubnet: {{ pod_subnet }}"

# initialize cluster
- name: initialize kubernetes cluster
  shell: kubeadm init --config /home/{{ user }}/kubeadm-master.yaml

# let root interact with newly created cluster
- name: create root .kube directory
  file:
    path: /root/.kube
    state: directory
    mode: 0755

- name: copy config to root home
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes

# let user interact with newly created cluster
- name: create user .kube directory
  file:
    path: /home/{{ user }}/.kube
    state: directory
    mode: 0755

- name: copy config to user home
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ user }}/.kube/config
    remote_src: yes
    owner: "{{ user }}"

# install flannel for cloud nodes
- name: copy flannel-cloud yaml
  copy:
    src: ../files/kube-flannel-cloud.yaml
    dest: /home/{{ user }}/kube-flannel-cloud.yaml

- name: install flannel network in cloud
  shell: kubectl apply -f /home/{{ user }}/kube-flannel-cloud.yaml

# install flannel for edge nodes
# https://github.com/kubeedge/kubeedge/issues/4521
- name: copy flannel-edge yaml
  copy:
    src: ../files/kube-flannel-edge.yaml
    dest: /home/{{ user }}/kube-flannel-edge.yaml

- name: install flannel network in edge
  shell: kubectl apply -f /home/{{ user }}/kube-flannel-edge.yaml

# kubeedge rejects kube-proxy by default 
# configure kube-proxy to no be deployed on edge nodes
# - name: patch edge nodes
#   shell: ' kubectl patch daemonset kube-proxy -n kube-system -p '{"spec": {"template": {"spec": {"affinity": {"nodeAffinity": {"requiredDuringSchedulingIgnoredDuringExecution": {"nodeSelectorTerms": [{"matchExpressions": [{"key": "node-role.kubernetes.io/edge", "operator": "DoesNotExist"}]}]}}}}}}}' '

# Copy the join command in a file so cloud nodes can copy it later
- name: Get the token for joining the worker nodes
  shell: kubeadm token create  --print-join-command
  register: join_command

# print join command in console
- debug:
    msg: "{{ join_command.stdout }}"

- name:  copy join command to file in user home
  copy:
    content: "{{ join_command.stdout_lines[0] }}"
    dest: /etc/kubernetes/cluster_join_command.sh
    mode: '0777'