---
- hosts: master
  become: yes     # root privileges
  tasks:
  - name: fetch kubectl config file
    fetch:
      src: /root/.kube/config
      dest: /tmp/kube-config
      flat: yes   # override the default behavior of appending hostname/path/to/file to the destination

- hosts: edge
  become: yes     # root privileges
  roles:
    - role: edgecore-join
      cloudcore_ip: 192.168.50.21
    #- role: keadm-join
    #  user: acanete
    #  cloudcore_ip: 192.168.50.21
    #  kubeedge_version: v1.14.0     # edgecore version