---
- name: install dependency packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
    state: latest
    update_cache: true

- name: create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory

- name: download apt key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc

- name: add docker apt repository
  apt_repository:
    repo: "deb [arch={{ arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: /etc/apt/sources.list.d/docker

- name: install containerd
  apt:
    name: containerd
    state: present
    update_cache: yes

- name: create containerd directory
  file:
    path: /etc/containerd
    state: directory

- name: copy containerd config
  copy:
    src: ../files/containerd.toml
    dest: /etc/containerd/config.toml

- name: restart containerd
  systemd:
    name: containerd
    daemon_reload: true
    enabled: true
    state: restarted