---
# clean previous edgecore installations
- name: remove kubeedge directory
  file:
    path: /etc/kubeedge
    state: absent

# let root interact with the cluster
- name: create root .kube directory
  file:
    path: /root/.kube
    state: directory
    mode: 0755

- name: copy config to root home
  copy:
    src: /tmp/kube-config
    dest: /root/.kube/config

# let user interact with the cluster
- name: create user .kube directory
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    mode: 0755

- name: copy config to user home
  copy:
    src: /tmp/kube-config
    dest: /root/.kube/config
    owner: "{{ ansible_user }}"

# create and set edgecore config file
- name: create kubeedge config directory
  file:
    path: /etc/kubeedge/config
    state: directory

# edgecore --defaultconfig > /etc/kubeedge/config/edgecore.yaml
- name: copy edgecore config file
  copy:
    src: ../files/edgecore.yaml
    dest: /etc/kubeedge/config/edgecore.yaml

# TODO: set podSandboxImage depending on architecture https://kubeedge.io/en/docs/setup/config/#modification-in-edgecore-yaml

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/replace_module.html
- name: set the cloudcore IP in edgecore config
  replace: 
    path: /etc/kubeedge/config/edgecore.yaml
    regexp: "CLOUDCORE_IP"
    replace: "{{ cloudcore_ip }}"

# set the edgecore node IP 
- name: set nodeIP in config file
  lineinfile:
    path: /etc/kubeedge/config/edgecore.yaml
    search_string: "    nodeIP:"
    line: "    nodeIP: {{ ansible_default_ipv4.address }}"  # !! all jetsons have eth0 and eth0 is ansible's default

# set the edgecore hostname
- name: set hostname in config file
  lineinfile:
    path: /etc/kubeedge/config/edgecore.yaml
    search_string: "    hostnameOverride:"
    line: "    hostnameOverride: {{ inventory_hostname }}" 

# get the cloudcore join token
- name: get kubeedge cluster join token
  shell: "kubectl get secret -n kubeedge tokensecret -o=jsonpath='{.data.tokendata}' | base64 -d"
  register: token

# print token in console
- debug:
    msg: "{{ token.stdout }}"

- name: set token in config file
  lineinfile:
    path: /etc/kubeedge/config/edgecore.yaml
    search_string: "    token:"
    line: "    token: {{ token.stdout_lines[0] }}"  

# set edgecore and systemd service
- name: download edgecore service file
  get_url:
    url: "https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/tools/edgecore.service"
    dest: /etc/systemd/system/edgecore.service

- name: start edgecore
  systemd:
    name: edgecore
    daemon_reload: true
    enabled: true
    state: restarted